### ISSUE TITLE
Feature request: open post's links in a new tab

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroMe#64]

**Comment by owintwist** [comment]
Please don't.

**Comment by Plasmmer** [comment]
??

**Comment by owintwist** [comment]
Bon.

tltr: don't force link to open in new tabs, because someones don't like.

En fait il existe dans les navigateurs, 3 méthodes pour ouvrir n'importe quel lien dans un nouvel onglet (clic-droit/long-touch > ouvrir dans un nouvel onglet , MiddleClic et Ctrl+Clic).
Or il n'existe _aucune_ méthode qui permet d'ouvrir un lien ayant un target="_blank", dans l'onglet en cours.

C'est un débat aussi vieux que le W3C, et il est globalement admis qu'il faut laisser l'utilisateur libre de choisir sa façon de surfer (donc de ne pas forcer l'ouverture dans un nouvel onglet).  
Voici donc pourquoi je demande à ce que cette _Feature Request_ ne soit pas retenue.

Sorry for my lack of vocabulary…

**Comment by Plasmmer** [comment]
Isn't a good practice open external links in the same tab.

**Comment by owintwist** [comment]
Bye.

**Comment by HelloZeroNet** [comment]
Actually this is because technical limitation. ZeroNet running sites sandboxed iframe where the links with target="_blank" does not work properly in every browser.
Probably related to https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by Plasmmer** [comment]
iframes can communicate with the main frame with JavaScript. You can create a API for it.
When user clicks a link (that is modified for the code work), then the main receives this message with the link metadata, and then does the work.

**Comment by owintwist** [comment]
Sounds interresting. That must be a way to add a switch. ^^

**Comment by Plasmmer** [comment]
@mkg20001 do you think its impossible?

**Comment by Plasmmer** [comment]
Already in: https://github.com/mkg20001/ZeroMe/issues/77.
